/**
 * Report UI definitions — filters, columns, validation.
 * Data is loaded via GET /api/internal-user/reports/:reportId
 */

export const COA_SPOT_OPTIONS = [
  { value: '1', label: 'Spot' },
  { value: '2', label: 'COA' },
];

export const REPORT_DEFINITIONS = {
  'spot-fixtures-report': {
    title: 'Spot Fixtures Report',
    searchOnMount: false,
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From (financial year)', type: 'date' },
      { key: 'dateTo', label: 'Date To (financial year)', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: 'Sr. No' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'owner', label: 'Owner' },
      { key: 'broker', label: 'Broker' },
      { key: 'vesselType', label: 'Vessel Type' },
      { key: 'contractQty', label: 'Contract Qty (MT)' },
      { key: 'loadPort', label: 'Load Port' },
      { key: 'dischargePort', label: 'Discharge Port' },
      { key: 'freight', label: 'Freight (USD)' },
    ],
  },

  'chartering-register-coa-spot': {
    title: 'Chartering Register - COA/SPOT',
    searchOnMount: false,
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From', type: 'date' },
      { key: 'dateTo', label: 'Date To', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selCOASpot', label: 'COA/Spot', type: 'coaSpot', defaultValue: '1' },
    ],
    columns: [
      { key: 'srNo', label: 'Sr. No.' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyage', label: 'Voyage No./ Name' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpic', label: 'CPIC' },
      { key: 'opsPic', label: 'OPS PIC' },
      { key: 'dwt', label: 'DWT' },
      { key: 'cargoName', label: 'Cargo Name' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'ownerName', label: 'Owner Name' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'fixtureDate', label: 'Fixture Date' },
      { key: 'revenue', label: 'Revenue' },
      { key: 'initialPl', label: 'Initial P & L', mgmtOnly: true },
      { key: 'finalPl', label: 'Final P & L', mgmtOnly: true },
      { key: 'remarks', label: 'Remarks' },
    ],
  },

  'chartering-register-detailed-coa-spot': {
    title: 'Chartering Register - Detailed - COA/SPOT',
    searchOnMount: false,
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From', type: 'date' },
      { key: 'dateTo', label: 'Date To', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selCOASpot', label: 'COA/Spot', type: 'coaSpot', defaultValue: '1' },
    ],
    columns: [
      { key: 'srNo', label: 'Sr. No.' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpic', label: 'CPIC' },
      { key: 'opsPic', label: 'OPS PIC' },
      { key: 'dwt', label: 'DWT' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'ownerName', label: 'Owner Name (TC Hire In)' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'fixtureDate', label: 'Fixture Date' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'initialPl', label: 'Initial P & L', mgmtOnly: true },
      { key: 'finalPl', label: 'Final P & L', mgmtOnly: true },
      { key: 'revenue', label: 'Revenue' },
      { key: 'remarks', label: 'Remarks' },
    ],
  },

  'chartering-register-tcs': {
    title: 'Chartering Register - TCs',
    searchOnMount: false,
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From', type: 'date' },
      { key: 'dateTo', label: 'Date To', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: 'Sr. No.' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'tcNo', label: 'TC No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'dwt', label: 'DWT(MT)' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'ports', label: 'Port Del/ Port Re-Del' },
      { key: 'dates', label: 'Del/Re-Del Dates' },
      { key: 'totalRev', label: 'Total Rev(USD)' },
      { key: 'otherExp', label: 'Other Expenses(USD)' },
      { key: 'tcInHire', label: 'TC In-Hire Expense(USD)' },
      { key: 'totalExp', label: 'Total Exp(USD)' },
      { key: 'tcEarnings', label: 'TC Earnings' },
      { key: 'profitPerDay', label: 'Profit/ Day (USD)', mgmtOnly: true },
    ],
  },

  'vessel-open-position-report': {
    title: 'Vessel Open Position Report',
    searchOnMount: true,
    filters: [
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'vesselType', label: 'Vessel Type' },
      { key: 'lastBusiness', label: 'Last Business(Voyage/TC)' },
      { key: 'lastPort', label: 'Last Dis Port/Port Open' },
      { key: 'dateOpen', label: 'Date Open' },
      { key: 'lastCargo', label: 'Last Cargo' },
      { key: 'lastCargoSize', label: 'Last Cargo Size(MT)' },
    ],
  },

  'tc-earning-report': {
    title: 'TC Earning Report',
    searchOnMount: false,
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From (CP Date)', type: 'date' },
      { key: 'dateTo', label: 'Date To (CP Date)', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: 'S.No.' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'tcDays', label: 'TC Days' },
      { key: 'pl', label: 'P&L (USD)' },
      { key: 'hirePerDay', label: 'Hire/Day (USD)' },
      { key: 'tcEarning', label: 'TC Earning (USD)' },
    ],
  },

  'vessel-tc-perf-against-baltic': {
    title: 'Vessel/TC Perf against Baltic',
    searchOnMount: true,
    filters: [],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'tcNo', label: 'TC No.' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'owner', label: 'Owner' },
      { key: 'delDate', label: 'Del Date' },
      { key: 'reDelDate', label: 'Re-Del Date' },
      { key: 'delPort', label: 'Del Port' },
      { key: 'reDelPort', label: 'Re-Del Port' },
      { key: 'dailyHire', label: 'Daily Hire(USD)' },
      { key: 'balticRoute', label: 'Baltic Route' },
      { key: 'balticDate', label: 'Baltic Route Date' },
      { key: 'balticValue', label: 'Baltic Route Value(USD)' },
      { key: 'tceDiff', label: 'TCE Diff' },
      { key: 'tceDiffPct', label: 'TCE Diff(%)' },
    ],
  },

  'da-tracker-chartering': {
    title: 'DA Tracker - CHARTERING',
    searchOnMount: false,
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selAgent', label: 'Port Cost Vendor', type: 'vendor', defaultValue: '' },
      { key: 'selCostType', label: 'Cost Type', type: 'costType', defaultValue: '' },
      { key: 'selPort', label: 'Ports', type: 'port', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: 'Sr No' },
      { key: 'fixtureNo', label: 'Fixture No.' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Dated' },
      { key: 'chtgPic', label: 'CHTG PIC' },
      { key: 'opcPic', label: 'OPC PIC' },
      { key: 'cargoType', label: 'Cargo Type' },
      { key: 'portName', label: 'Port Name' },
      { key: 'costType', label: 'Cost Type' },
      { key: 'portCostVendor', label: 'Port cost vendor' },
    ],
  },

  'approval-status-report': {
    title: 'Approval Status Report',
    searchOnMount: true,
    filters: [],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'formName', label: 'Form Name' },
      { key: 'invoiceNo', label: 'Invoice/Advice No' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vendorName', label: 'Vendor Name' },
      { key: 'status', label: 'Status' },
      { key: 'pendingWith', label: 'Pending With' },
      { key: 'editLink', label: 'Edit Link' },
    ],
  },

  'voyage-report-fleet': {
    title: 'Voyage Report - Fleet',
    searchOnMount: false,
    requiredFilters: ['vesselImoNo'],
    requiredMessage: 'Enter Vessel IMO (COMID is optional — use when opening from Ops).',
    filters: [
      { key: 'vesselImoNo', label: 'Vessel IMO', type: 'text' },
      { key: 'comId', label: 'Nomination COMID (optional)', type: 'text' },
      { key: 'selYear', label: 'Year', type: 'year' },
    ],
    columns: [
      { key: 'index', label: '#' },
      { key: 'reportTitle', label: 'Report Title/type' },
      { key: 'vesselType', label: 'Vessel Type' },
      { key: 'messageNo', label: 'Message No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'voyageNo', label: 'Voy No.' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'reportingLt', label: 'Reporting Date/Time(LT)' },
      { key: 'reportingUtc', label: 'Reporting Date/Time(UTC)' },
      { key: 'depPort', label: 'Dep Port' },
      { key: 'portOfArrival', label: 'Port Of Arrival' },
      { key: 'nextPort', label: 'Next Port' },
      { key: 'etaNextPort', label: 'ETA Next Port' },
    ],
  },
};

export const MANAGEMENT_REPORT_DEFINITIONS = {
  'comparison-report': {
    title: 'Comparison Report',
    pageType: 'comparison',
    searchOnMount: false,
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
    ],
    columns: [
      { key: 'srNo', label: 'S.No.' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cargoQty', label: 'Cargo Qty. (MT)' },
      { key: 'tcEarning', label: 'TC Earning (USD)' },
      { key: 'pl', label: 'P&L (USD)' },
      { key: 'compare', label: 'Comparison', action: 'compareSheets' },
    ],
  },

  'pl-at-a-glance-vc': {
    title: 'P & L At a Glance-VC',
    searchOnMount: false,
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selTeam', label: 'Team', type: 'team', defaultValue: '' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: 'Sno.' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'charterer', label: 'Charterers' },
      { key: 'team1', label: 'Chartering Team 1' },
      { key: 'team2', label: 'Chartering Team 2' },
      { key: 'pic1', label: 'Chartering Pic 1' },
      { key: 'pic2', label: 'Chartering Pic 2' },
      { key: 'pic3', label: 'Chartering Pic 3' },
      { key: 'year', label: 'Year' },
      { key: 'initialPl', label: 'Initial P & L' },
      { key: 'finalPl', label: 'Final P & L' },
    ],
  },

  'pl-at-a-glance-vc-tc': {
    title: 'P & L At a Glance-VC/TC',
    pageType: 'dualPl',
    searchOnMount: false,
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selTeam', label: 'Team', type: 'team', defaultValue: '' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    vcTitle: 'VC',
    tcTitle: 'TC',
    vcColumns: [
      { key: 'srNo', label: 'Sno.' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'charterer', label: 'Charterers' },
      { key: 'team1', label: 'Chartering Team 1' },
      { key: 'team2', label: 'Chartering Team 2' },
      { key: 'pic1', label: 'Chartering Pic 1' },
      { key: 'pic2', label: 'Chartering Pic 2' },
      { key: 'pic3', label: 'Chartering Pic 3' },
      { key: 'year', label: 'Year' },
      { key: 'initialPl', label: 'Initial P & L' },
      { key: 'finalPl', label: 'Final P & L' },
    ],
    tcColumns: [
      { key: 'srNo', label: 'Sno.' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'charterer', label: 'Charterers' },
      { key: 'team', label: 'Chartering Team' },
      { key: 'pic1', label: 'Chartering Pic 1' },
      { key: 'pic2', label: 'Chartering Pic 2' },
      { key: 'ownerName', label: 'Owner Name (TC Hire In)' },
      { key: 'tcEarnings', label: 'TC Earnings' },
    ],
  },

  'pl-at-a-glance-tc': {
    title: 'P & L At a Glance-TC',
    searchOnMount: false,
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selTeam', label: 'Team', type: 'team', defaultValue: '' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: 'Sno.' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'charterer', label: 'Charterers' },
      { key: 'team', label: 'Chartering Team' },
      { key: 'pic1', label: 'Chartering Pic 1' },
      { key: 'pic2', label: 'Chartering Pic 2' },
      { key: 'ownerName', label: 'Owner Name (TC Hire In)' },
      { key: 'tcEarningsInitial', label: 'TC Earnings (Initial)' },
      { key: 'tcEarnings', label: 'TC Earnings' },
    ],
  },

  'cargo-tonnage-report': {
    title: 'Cargo Tonnage Report',
    pageType: 'cargoTonnage',
    searchOnMount: false,
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From (CP From)', type: 'date' },
      { key: 'dateTo', label: 'Date To (CP Date To)', type: 'date' },
    ],
    columns: [
      { key: 'cargoName', label: 'Cargo Name' },
      { key: 'cargoQty', label: 'Cargo Quantity (MT)' },
    ],
  },
};

Object.assign(REPORT_DEFINITIONS, MANAGEMENT_REPORT_DEFINITIONS);

export function getReportDefinition(reportId) {
  return REPORT_DEFINITIONS[reportId] || null;
}

export const CHARTERING_REPORT_IDS = [
  'da-tracker-chartering',
  'approval-status-report',
  'vessel-tc-perf-against-baltic',
  'vessel-open-position-report',
  'spot-fixtures-report',
  'chartering-register-coa-spot',
  'chartering-register-detailed-coa-spot',
  'chartering-register-tcs',
  'tc-earning-report',
  'voyage-report-fleet',
];

export const MANAGEMENT_REPORT_IDS = Object.keys(MANAGEMENT_REPORT_DEFINITIONS);

export const OPERATIONS_REPORT_DEFINITIONS = {
  'voyage-details': {
    title: 'Voyage Details',
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From (CP date)', type: 'date' },
      { key: 'dateTo', label: 'Date To (CP date)', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selCOASpot', label: 'COA/Spot', type: 'coaSpot', defaultValue: '1' },
    ],
    columns: [
      { key: 'srNo', label: 'Sno.' },
      { key: 'voyageId', label: 'Voyage ID' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpic', label: 'CPIC' },
      { key: 'opsPic', label: 'OPS PIC' },
      { key: 'dwt', label: 'DWT' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'ownerName', label: 'Owner Name (TC Hire In)' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'fixtureDate', label: 'Fixture Date' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'pl', label: 'P & L' },
    ],
  },
  'agent-list': {
    title: 'Agent List',
    searchOnMount: true,
    filters: [
      { key: 'selPort', label: 'Port', type: 'port', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'voyageName', label: 'Voyage Name' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'port', label: 'Port' },
      { key: 'cargo', label: 'Cargo' },
      { key: 'agent', label: 'Agent' },
      { key: 'shipper', label: 'Shipper' },
    ],
  },
  'bunker-consumption-report': {
    title: 'Bunker Consumption Report',
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From', type: 'date' },
      { key: 'dateTo', label: 'Date To', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selVessel', label: 'Vessel', type: 'vessel', defaultValue: '' },
      { key: 'selCOASpot', label: 'COA/Spot', type: 'coaSpot', defaultValue: '1' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'bunkerSummary', label: 'Bunker Summary' },
    ],
  },
  'daily-position-report': {
    title: 'Daily Position Report',
    searchOnMount: true,
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selVoyageType', label: 'Voyage Type', type: 'voyageType', defaultValue: 'VC' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'loadPort', label: 'Load Port' },
      { key: 'dischargePort', label: 'Discharge Port' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'status', label: 'Status' },
    ],
  },
  'dead-freight-summary': {
    title: 'Dead Freight Summary',
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From', type: 'date' },
      { key: 'dateTo', label: 'Date To', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'chk', label: 'Remove Zeros', type: 'checkbox', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: 'Sr. No' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'coaSpot', label: 'COA/Spot' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'shipper', label: 'Shipper' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'loadPort', label: 'Load Port' },
      { key: 'dischargePort', label: 'Discharge Port' },
      { key: 'contractQty', label: 'Contract Qty (MT)' },
      { key: 'deadFreightQty', label: 'Dead freight Qty (MT)' },
      { key: 'deadFreightAmt', label: 'Dead freight Amount (USD)' },
    ],
  },
  'demurrage-summary': {
    title: 'Demmurage Summary',
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From', type: 'date' },
      { key: 'dateTo', label: 'Date To', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selCOASpot', label: 'COA/Spot', type: 'coaSpot', defaultValue: '1' },
      { key: 'chk', label: 'Remove Zeros', type: 'checkbox', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'loadPort', label: 'Load Port' },
      { key: 'dischargePort', label: 'Discharge Port' },
      { key: 'demurrageAmt', label: 'Demurrage Amount (USD)' },
    ],
  },
  'headwise-expense-report': {
    title: 'Headwise Expense Report',
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From', type: 'date' },
      { key: 'dateTo', label: 'Date To', type: 'date' },
      { key: 'selVendor', label: 'Vendor', type: 'vendor', defaultValue: '' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selCOASpot', label: 'COA/Spot', type: 'coaSpot', defaultValue: '1' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'bunkerExpenses', label: 'Bunker Expenses' },
      { key: 'portExpenses', label: 'Port Expenses' },
      { key: 'totalExpenses', label: 'Total Expenses' },
      { key: 'pl', label: 'P & L' },
    ],
  },
  'port-performance-report': {
    title: 'Port Performance Report',
    searchOnMount: true,
    filters: [
      { key: 'selPort', label: 'Port', type: 'port', defaultValue: '' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'loadPort', label: 'Load Port' },
      { key: 'dischargePort', label: 'Discharge Port' },
      { key: 'cargo', label: 'Cargo' },
      { key: 'charterer', label: 'Charterer' },
    ],
  },
  'detailed-register': {
    title: 'Detailed Register',
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selTeam', label: 'Team', type: 'team', defaultValue: '' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selCOASpot', label: 'COA/Spot', type: 'coaSpot', defaultValue: '1' },
    ],
    columns: [
      { key: 'srNo', label: 'Sno.' },
      { key: 'voyageId', label: 'Voyage ID' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpic', label: 'CPIC' },
      { key: 'opsPic', label: 'OPS PIC' },
      { key: 'dwt', label: 'DWT' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'ownerName', label: 'Owner Name' },
      { key: 'charterer', label: 'Charterer' },
      { key: 'fixtureDate', label: 'Fixture Date' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'pl', label: 'P & L' },
    ],
  },
  'hire-expense-details-vc': {
    title: 'Hire Expense Details(Vc)',
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From (CP date)', type: 'date' },
      { key: 'dateTo', label: 'Date To (CP date)', type: 'date' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel Name' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'hireDays', label: 'Hire Days' },
      { key: 'hireAmt', label: 'Hire Amount' },
      { key: 'pfhsAmount', label: 'PFHS Amount' },
      { key: 'lastUpdatedBy', label: 'Last Updated By' },
      { key: 'lastUpdatedAt', label: 'Last Updated At' },
    ],
  },
  'ffi-tracker-vc-out': {
    title: 'FFI Tracker (VC OUT)',
    pageType: 'editableTracker',
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selTeam', label: 'Team', type: 'team', defaultValue: '' },
    ],
    fixedColumns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'charterer', label: 'Charterer' },
    ],
    editableColumns: [
      { key: 'ffispostfix', label: 'Post Fix' },
      { key: 'lpstatuslaytime', label: 'LP Status' },
      { key: 'dpstatuslaytime', label: 'DP Status' },
      { key: 'ffistatus', label: 'FFI Status' },
      { key: 'FFISentDate', label: 'FFI Sent Date', inputType: 'date' },
      { key: 'add_rem', label: 'Remarks' },
    ],
  },
  'ffi-tracker-vc-in': {
    title: 'FFI Tracker (VC IN)',
    pageType: 'editableTracker',
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selTeam', label: 'Team', type: 'team', defaultValue: '' },
    ],
    fixedColumns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'charterer', label: 'Charterer' },
    ],
    editableColumns: [
      { key: 'ffispostfix', label: 'Post Fix' },
      { key: 'lpstatuslaytime', label: 'LP Status' },
      { key: 'dpstatuslaytime', label: 'DP Status' },
      { key: 'ffistatus', label: 'FFI Status' },
      { key: 'FFISentDate', label: 'FFI Sent Date', inputType: 'date' },
      { key: 'add_rem', label: 'Remarks' },
    ],
  },
  'ffi-brokerage-tracker': {
    title: 'FFI Brokerage Tracker',
    pageType: 'editableTracker',
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selTeam', label: 'Team', type: 'team', defaultValue: '' },
    ],
    fixedColumns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'charterer', label: 'Charterer' },
    ],
    editableColumns: [
      { key: 'laytimefile', label: 'Laytime File' },
      { key: 'status', label: 'Status' },
      { key: 'add_remarks', label: 'Remarks' },
    ],
  },
  'fhs-brokerage-tracker-vc': {
    title: 'FHS & Brokerage Tracker (VC)',
    pageType: 'editableTracker',
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selTeam', label: 'Team', type: 'team', defaultValue: '' },
    ],
    fixedColumns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'charterer', label: 'Charterer' },
    ],
    editableColumns: [
      { key: 'Owners_Status', label: 'Owners Status' },
      { key: 'Bainbridge_Status', label: 'Bainbridge Status' },
      { key: 'out_amt_as_per_owner', label: 'Out Amt (Owner)' },
      { key: 'out_amt_as_per_bb', label: 'Out Amt (BB)' },
      { key: 'last_rem_date', label: 'Last Rem Date', inputType: 'date' },
      { key: 'add_rem', label: 'Remarks' },
    ],
  },
  'fhs-brokerage-tracker-tc-expense': {
    title: 'FHS & Brokerage Tracker TC Expense',
    pageType: 'editableTracker',
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selTeam', label: 'Team', type: 'team', defaultValue: '' },
    ],
    fixedColumns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'TC No.' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'charterer', label: 'Charterer' },
    ],
    editableColumns: [
      { key: 'Owners_Status', label: 'Owners Status' },
      { key: 'Bainbridge_Status', label: 'Bainbridge Status' },
      { key: 'out_amt_as_per_owner', label: 'Out Amt (Owner)' },
      { key: 'out_amt_as_per_bb', label: 'Out Amt (BB)' },
      { key: 'last_rem_date', label: 'Last Rem Date', inputType: 'date' },
      { key: 'add_rem', label: 'Remarks' },
    ],
  },
  'fhs-brokerage-tracker-tc-income': {
    title: 'FHS & Brokerage Tracker TC Income',
    pageType: 'editableTracker',
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selTeam', label: 'Team', type: 'team', defaultValue: '' },
    ],
    fixedColumns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'TC No.' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'charterer', label: 'Charterer' },
    ],
    editableColumns: [
      { key: 'Owners_Status', label: 'Owners Status' },
      { key: 'Bainbridge_Status', label: 'Bainbridge Status' },
      { key: 'out_amt_as_per_owner', label: 'Out Amt (Owner)' },
      { key: 'out_amt_as_per_bb', label: 'Out Amt (BB)' },
      { key: 'last_rem_date', label: 'Last Rem Date', inputType: 'date' },
      { key: 'add_rem', label: 'Remarks' },
    ],
  },
  'da-tracker-ops-post-ops': {
    title: 'DA Tracker - Ops & Post Ops',
    pageType: 'editableTracker',
    requiredFilters: ['selYear'],
    requiredMessage: 'Please select Year.',
    filters: [
      { key: 'selYear', label: 'Year', type: 'year' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selAgent', label: 'Port Cost Vendor', type: 'vendor', defaultValue: '' },
      { key: 'selCostType', label: 'Cost Type', type: 'costType', defaultValue: '' },
      { key: 'selPort', label: 'Ports', type: 'port', defaultValue: '' },
    ],
    fixedColumns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'charterer', label: 'Charterer' },
    ],
    editableColumns: [
      { key: 'Owners_Status', label: 'Owners Status' },
      { key: 'Bainbridge_Status', label: 'Bainbridge Status' },
      { key: 'charterers_agent', label: 'Charterers Agent' },
      { key: 'agency_fees', label: 'Agency Fees' },
    ],
  },
};

Object.assign(REPORT_DEFINITIONS, OPERATIONS_REPORT_DEFINITIONS);

export const OPERATIONS_REPORT_IDS = Object.keys(OPERATIONS_REPORT_DEFINITIONS);

export const ACCOUNTS_REPORT_DEFINITIONS = {
  'aging-report-payable': {
    title: 'Aging Report (Payable)',
    filters: [
      { key: 'selDateType', label: 'Days', type: 'daySelection', defaultValue: '1' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selCOASpot', label: 'COA/Spot', type: 'coaSpot', defaultValue: '1' },
      { key: 'selVendor', label: 'Vendor', type: 'vendor', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'vendor', label: 'Vendor' },
      { key: 'coaSpot', label: 'COA/Spot' },
      { key: 'nomId', label: 'Nom ID / Voyage' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'costType', label: 'Cost Type' },
      { key: 'paymentNo', label: 'Payment No.' },
      { key: 'invoiceDate', label: 'Invoice Date' },
      { key: 'paymentDate', label: 'Payment Date' },
      { key: 'amountInvoiced', label: 'Amount Invoiced' },
      { key: 'amountPaid', label: 'Amount Paid' },
      { key: 'difference', label: 'Difference' },
      { key: 'delayDays', label: 'Delay (Days)' },
    ],
  },
  'aging-report-receivables': {
    title: 'Aging Report (Receivables)',
    filters: [
      { key: 'selDateType', label: 'Days', type: 'daySelection', defaultValue: '1' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selSpotCOA', label: 'Spot/COA/TC', type: 'spotCoaTc', defaultValue: '1' },
      { key: 'selVendor', label: 'Client', type: 'vendor', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'client', label: 'Client' },
      { key: 'spotCoaTc', label: 'Spot/COA/TC' },
      { key: 'nomId', label: 'Nom ID / Voyage' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'invoiceType', label: 'Invoice Type' },
      { key: 'invoiceNo', label: 'Invoice No.' },
      { key: 'invoiceDate', label: 'Invoice Date' },
      { key: 'amountInvoiced', label: 'Amount Invoiced' },
      { key: 'amountReceived', label: 'Amount Received' },
      { key: 'difference', label: 'Difference' },
      { key: 'delayDays', label: 'Delay (Days)' },
      { key: 'openClosed', label: 'Open/Closed' },
    ],
  },
  'payable-receivables-report': {
    title: 'Payable & Receivables Report',
    requiredFilters: ['selVendor'],
    requiredMessage: 'Please select Vendor/Client.',
    filters: [
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selSpotCOA', label: 'Spot/COA/TC', type: 'spotCoaTc', defaultValue: '1' },
      { key: 'selVendor', label: 'Vendor/Client', type: 'vendor', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'client', label: 'Client' },
      { key: 'spotCoaTc', label: 'Spot/COA/TC' },
      { key: 'nomId', label: 'Nom ID / Voyage' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'amountInvoiced', label: 'Amount Invoiced' },
      { key: 'amountReceived', label: 'Amount Received' },
      { key: 'recvDifference', label: 'Recv. Difference' },
      { key: 'paymentAdvice', label: 'Payment Advice' },
      { key: 'amountPaid', label: 'Amount Paid' },
      { key: 'payDifference', label: 'Pay Difference' },
    ],
  },
  'profitability-analysis-coa-spot': {
    title: 'Profitability Analysis - COA/Spot',
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From (CP date)', type: 'date' },
      { key: 'dateTo', label: 'Date To (CP date)', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selCOASpot', label: 'COA/Spot', type: 'coaSpot', defaultValue: '1' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'coaSpotVoyage', label: 'COA/Spot / Voyage' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'status', label: 'Status' },
      { key: 'totalQty', label: 'Total Qty' },
      { key: 'earnings', label: 'Earnings' },
      { key: 'expense', label: 'Expense' },
      { key: 'netEarnings', label: 'Net Earnings / P&L' },
    ],
  },
  'projected-cash-flow-vc': {
    title: 'Projected Cash Flow (VC)',
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From', type: 'date' },
      { key: 'dateTo', label: 'Date To', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
      { key: 'selAmountType', label: 'Amount Type', type: 'amountType', defaultValue: '1' },
      { key: 'txtDays', label: 'Days (+)', type: 'text', defaultValue: '0' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'nomId', label: 'Nom ID' },
      { key: 'materialName', label: 'Material' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'totalOutstanding', label: 'Total Outstanding' },
      { key: 'payments', label: 'Payments' },
      { key: 'balanceOutstanding', label: 'Balance Outstanding' },
      { key: 'lpDate', label: 'LP / Invoice Date' },
      { key: 'dueDate', label: 'Due Date' },
    ],
  },
  'shipment-register': {
    title: 'Shipment Register',
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Date From', type: 'date' },
      { key: 'dateTo', label: 'Date To', type: 'date' },
      { key: 'selDateType', label: 'Date Type', type: 'shipmentDateType', defaultValue: '2' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    columns: [
      { key: 'nomId', label: 'Nom ID' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'cpDate', label: 'CP Date' },
      { key: 'owner', label: 'Owner' },
      { key: 'broker', label: 'Broker' },
      { key: 'materialDesc', label: 'Material' },
      { key: 'lastUpdatedFreight', label: 'Freight' },
      { key: 'fromPort', label: 'From Port' },
      { key: 'toPort', label: 'To Port' },
      { key: 'blDate', label: 'BL Date' },
      { key: 'qty', label: 'Qty' },
      { key: 'portExpenses', label: 'Port Expenses' },
      { key: 'bunkerExpenses', label: 'Bunker Expenses' },
      { key: 'voyageEarnings', label: 'Voyage Earnings' },
      { key: 'dailyEarnings', label: 'Daily Earnings' },
      { key: 'pl', label: 'P & L' },
    ],
  },
  'payment-actioned-report': {
    title: 'Payment Actioned Report',
    requiredFilters: ['dateFrom', 'dateTo'],
    requiredMessage: 'Please select Date From and Date To.',
    filters: [
      { key: 'dateFrom', label: 'Payment Date From', type: 'date' },
      { key: 'dateTo', label: 'Payment Date To', type: 'date' },
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'voyageNo', label: 'Voyage No.' },
      { key: 'vesselName', label: 'Vessel' },
      { key: 'vendorName', label: 'Vendor' },
      { key: 'paymentType', label: 'Payment Type' },
      { key: 'paymentDate', label: 'Payment Date' },
      { key: 'amount', label: 'Amount' },
    ],
  },
};

Object.assign(REPORT_DEFINITIONS, ACCOUNTS_REPORT_DEFINITIONS);

export const ACCOUNTS_REPORT_IDS = Object.keys(ACCOUNTS_REPORT_DEFINITIONS);

export const GRAPHICAL_REPORT_DEFINITIONS = {
  'vessel-yearly-performance': {
    title: 'Vessel Yearly Performance',
    pageType: 'vesselYearly',
    searchOnMount: true,
    filters: [
      { key: 'selBType', label: 'Business Type', type: 'businessType', defaultValue: '' },
    ],
    columns: [
      { key: 'srNo', label: '#' },
      { key: 'year', label: 'Year' },
      { key: 'total', label: 'Total' },
    ],
  },
};

Object.assign(REPORT_DEFINITIONS, GRAPHICAL_REPORT_DEFINITIONS);

export const GRAPHICAL_REPORT_IDS = Object.keys(GRAPHICAL_REPORT_DEFINITIONS);

export const LIVE_REPORT_IDS = [
  ...CHARTERING_REPORT_IDS,
  ...MANAGEMENT_REPORT_IDS,
  ...OPERATIONS_REPORT_IDS,
  ...ACCOUNTS_REPORT_IDS,
  ...GRAPHICAL_REPORT_IDS,
];

