/** Shared Add/Update estimate API payload from computed form state. */
export function buildEstimateSubmitPayload(form, estimateType, periodId = null) {
  const filterCargo = (rows) => (rows || []).filter((row) => row.cargoId || row.cargoMt);

  return {
    fixtureTypeId: form.fixtureTypeId != null && String(form.fixtureTypeId).trim() !== ''
      ? Number(form.fixtureTypeId)
      : null,
    vesselImoId: form.vesselImoId ? Number(form.vesselImoId) : null,
    estimateType: Number(estimateType),
    periodId: form.periodId || periodId || null,
    vesselType: form.vesselType,
    flag: form.flag,
    transDate: form.transDate,
    voyageNo: form.voyageNo,
    voyageName: form.voyageName || form.voyageNo,
    dwtSummer: form.dwtSummer,
    dwtTropical: form.dwtTropical,
    gnrt: form.gnrt,
    nrt: form.nrt,
    loa: form.loa,
    tpc: form.tpc,
    gear: form.gear,
    builtYear: form.builtYear,
    beam: form.beam,
    loadable: form.loadable,
    stowageFactor: form.stowageFactor,
    grainCap: form.grainCap,
    baleCap: form.baleCap,
    cargoQuantity: form.cargoQuantity,
    cargoIds: [
      ...new Set(
        [
          ...(form.cargoIds || []),
          ...(form.cargoRows || []).map((row) => row.cargoId),
          ...(form.overageCargoRows || []).map((row) => row.cargoId),
          ...(form.deadfreightCargoRows || []).map((row) => row.cargoId),
        ]
          .map((id) => String(id || '').trim())
          .filter((id) => id && id !== '0'),
      ),
    ],
    totalDays: form.totalDays,
    totalDistance: form.totalDistance,
    dailyEarning: form.dailyEarning,
    profitLoss: form.profitLoss,
    freightGross: form.freightGross,
    brokeragePercent: form.brokeragePercent,
    brokerageAmt: form.brokerageAmt,
    brokerRows: (form.brokerRows || []).filter(
      (row) => row.percent || row.amount || row.vendorId,
    ),
    hireRate: form.hireRate,
    hireAmt: form.hireAmt,
    cvePerMonth: form.cvePerMonth,
    cveAmt: form.cveAmt,
    offHireCve: form.offHireCve,
    offHireCveAmt: form.offHireCveAmt,
    lessOffHire: form.lessOffHire,
    ballastBonus: form.ballastBonus,
    hireagePercent: form.hireagePercent,
    hireageBroPercent: form.hireageBroPercent,
    lumpsum: form.lumpsum,
    lumpsumQty: form.lumpsumQty,
    chkLumpsum: !!form.chkLumpsum,
    lumpsumVendor: form.lumpsumVendor || '',
    marketRate: form.tankerFreightRate || form.marketRate,
    tankerFreightRate: form.tankerFreightRate || form.marketRate,
    tankType: form.tankType || '1',
    addCommPercent: form.addCommPercent,
    addressCommAmt: form.addressCommAmt,
    co2Price: form.co2Price,
    euaPrice: form.euaPrice,
    sdrToUsd: form.sdrToUsd,
    sdrToUsd: form.sdrToUsd,
    scnt: form.scnt,
    tankWsFrom: form.tankWsFrom
      || (form.tankerWsRows || [])[0]?.wsFromPortId
      || null,
    tankWsTo: form.tankWsTo
      || (form.tankerWsRows || [])[0]?.wsToPortId
      || null,
    vesselDailyOps: form.vesselDailyOps,
    cveVendorId: form.cveVendorId,
    chkHire: !!form.chkHire,
    chkIndex: !!form.chkIndex,
    balticIndex: form.balticIndex,
    balticPercent: form.balticPercent,
    balticRate: form.balticRate,
    dtcVendorId: form.dtcVendorId,
    brokerageVendorId: form.brokerageVendorId,
    tcCpDate: form.tcCpDate,
    tcDeliveryRange: form.tcDeliveryRange,
    tcRedeliveryRange: form.tcRedeliveryRange,
    tcDeliveryDate: form.tcDeliveryDate,
    tcRedeliveryDate: form.tcRedeliveryDate,
    timeAllowed: form.timeAllowed,
    laycanStart: form.laycanStart,
    laycanEnd: form.laycanEnd,
    demurrageBrokerPercent: form.demurrageBrokerPercent,
    euEtsAddToFreight: !!form.euEtsAddToFreight,
    fuelEuAddToFreight: !!form.fuelEuAddToFreight,
    hsfoMt: form.hsfoMt,
    etsHsfoMt: form.etsHsfoMt,
    vlsfoMt: form.vlsfoMt,
    etsVlsfoMt: form.etsVlsfoMt,
    lsmgoMt: form.lsmgoMt,
    etsLsmgoMt: form.etsLsmgoMt,
    bunkerResultsCost: form.bunkerResultsCost || form.totalBunkerCost,
    eeoi: form.eeoi,
    cii: form.cii,
    eeoiCo2: form.eeoiCo2,
    co2mt: form.co2mt,
    co2Cost: form.co2Cost,
    euaCo2mt: form.euaCo2mt,
    euaCo2Usd: form.euaCo2Usd,
    hsfoIntensity: form.hsfoIntensity,
    hsfoTarget: form.hsfoTarget,
    vlsfoIntensity: form.vlsfoIntensity,
    vlsfoTarget: form.vlsfoTarget,
    lsmgoIntensity: form.lsmgoIntensity,
    lsmgoTarget: form.lsmgoTarget,
    hsfoPenalty: form.hsfoPenalty,
    hsfoPenaltyPerMt: form.hsfoPenaltyPerMt,
    vlsfoPenalty: form.vlsfoPenalty,
    vlsfoPenaltyPerMt: form.vlsfoPenaltyPerMt,
    lsmgoPenalty: form.lsmgoPenalty,
    lsmgoPenaltyPerMt: form.lsmgoPenaltyPerMt,
    totalCarbonCost: form.totalCarbonCost,
    charteringPic: form.charteringPic || null,
    charteringTeam: form.charteringTeam || null,
    bFullSpeed: form.bFullSpeed,
    bEcoSpeed1: form.bEcoSpeed1,
    bEcoSpeed2: form.bEcoSpeed2,
    lFullSpeed: form.lFullSpeed,
    lEcoSpeed1: form.lEcoSpeed1,
    lEcoSpeed2: form.lEcoSpeed2,
    bFoFullSpeed: form.bFoFullSpeed,
    lFoFullSpeed: form.lFoFullSpeed,
    bDoFullSpeed: form.bDoFullSpeed,
    lDoFullSpeed: form.lDoFullSpeed,
    pIfoFullSpeed: form.pIfoFullSpeed,
    pWfoFullSpeed: form.pWfoFullSpeed,
    pIdoFullSpeed: form.pIdoFullSpeed,
    pWdoFullSpeed: form.pWdoFullSpeed,
    totalBunkerCost: form.totalBunkerCost,
    totalPortCost: form.totalPortCost,
    revenue: form.revenue,
    voyageEarnings: form.voyageEarnings,
    notes: form.notes,
    openPort: form.openPort,
    zoneOpen: form.zoneOpen,
    fixtureBroker: form.fixtureBroker,
    coaSpot: form.coaSpot,
    coaNumber: form.coaNumber,
    coaNumberLift: form.coaNumberLift,
    noOfShipment: form.noOfShipment,
    cpDate: form.cpDate,
    etaDate: form.etaDate,
    ownerId: form.ownerId,
    disponentOwner: form.disponentOwner,
    gasBaltic: form.gasBaltic,
    gasBaseRate: form.gasBaseRate,
    addnlPremium: form.addnlPremium,
    baseRateFloat: form.baseRateFloat,
    baseRateFixed: form.baseRateFixed,
    baseRateAverage: form.baseRateAverage,
    grossFreightFloat: form.grossFreightFloat,
    grossFreightFixed: form.grossFreightFixed,
    grossFreightAverage: form.grossFreightAverage,
    netFreightFloat: form.netFreightFloat,
    netFreightFixed: form.netFreightFixed,
    netFreightAverage: form.netFreightAverage,
    tceFloat: form.tceFloat,
    tceFixed: form.tceFixed,
    tceAverage: form.tceAverage,
    portLegs: (form.portLegs || []).filter((leg) => leg.fromPortId || leg.toPortId),
    cargoRows: filterCargo(form.cargoRows).map((row) => ({ ...row, status: 1 })),
    overageCargoRows: filterCargo(form.overageCargoRows).map((row) => ({ ...row, status: 2 })),
    deadfreightCargoRows: filterCargo(form.deadfreightCargoRows).map((row) => ({ ...row, status: 3 })),
    bunkerRows: (form.bunkerRows || []).filter((row) => row.bunkerGradeId || row.qty),
    bunkerActivityRows: (form.bunkerActivityRows || []).filter(
      (row) => row.activity || row.bunkerGrade || row.qty || row.amount,
    ),
    orcRows: (form.orcRows || []).filter((row) => row.costId || row.amount),
    otherIncomeRows: (form.otherIncomeRows || []).filter((row) => row.description || row.amount),
    hireRows: (form.hireRows || []).filter((row) => row.hireDays || row.hireRate || row.hireAmt),
    secaBunkerRows: (form.secaBunkerRows || []).filter((row) => row.bunkerGradeId || row.qty),
    consumptionRows: (form.consumptionRows || []).filter(
      (row) => row.bunkerGradeId || row.balSecaFs || row.ladSecaFs,
    ),
    passageLocations: (form.passageLocations || []).filter(
      (row) => row.fromLocation || row.toLocation,
    ),
    freightQtyRows: (form.freightQtyRows || []).filter(
      (row) => row.vendorId || row.quantity || row.agreedGrossFreight,
    ),
    tankerWsRows: (form.tankerWsRows || []).filter(
      (row) => row.wsFromPortId || row.wsToPortId || row.freightSpecs || row.minCargoQty || row.totalAmount,
    ),
    offHireRows: (form.offHireRows || [])
      .filter((row) => row.reason || row.days || row.amount)
      .map((row) => ({
        ...row,
        bunkers: (row.bunkers || []).filter((b) => b.bunkerGradeId || b.qty || b.amount),
      })),
    deliveryBunkerRows: (form.deliveryBunkerRows || []).filter(
      (row) => row.bunkerGradeId || row.qty,
    ),
    redeliveryBunkerRows: (form.redeliveryBunkerRows || []).filter(
      (row) => row.bunkerGradeId || row.qty,
    ),
    invoiceRows: (form.invoiceRows || []).filter((row) => row.invoiceId),
    disponentRows: (form.disponentRows || []).filter((row) => row.name),
    voyageEventRows: (form.voyageEventRows || []).filter((row) => row.details || row.eventDate),
    profitSharingRows: (form.profitSharingRows || []).filter(
      (row) => row.vendorId || row.percentage,
    ),
  };
}
