/** Shared Add/Update estimate API payload from computed form state. */
export function buildEstimateSubmitPayload(form, estimateType, periodId = null) {
  const filterCargo = (rows) => (rows || []).filter((row) => row.cargoId || row.cargoMt);

  return {
    fixtureTypeId: form.fixtureTypeId ? Number(form.fixtureTypeId) : null,
    vesselImoId: form.vesselImoId ? Number(form.vesselImoId) : null,
    estimateType: Number(estimateType),
    periodId: periodId || null,
    vesselType: form.vesselType,
    flag: form.flag,
    transDate: form.transDate,
    voyageNo: form.voyageNo,
    voyageName: form.voyageName || form.voyageNo,
    dwtSummer: form.dwtSummer,
    dwtTropical: form.dwtTropical,
    gnrt: form.gnrt,
    loa: form.loa,
    tpc: form.tpc,
    gear: form.gear,
    builtYear: form.builtYear,
    beam: form.beam,
    loadable: form.loadable,
    stowageFactor: form.stowageFactor,
    grainCap: form.grainCap,
    baleCap: form.baleCap,
    cargoQuantity: form.cargoQuantity,
    totalDays: form.totalDays,
    totalDistance: form.totalDistance,
    dailyEarning: form.dailyEarning,
    profitLoss: form.profitLoss,
    freightGross: form.freightGross,
    brokeragePercent: form.brokeragePercent,
    brokerageAmt: form.brokerageAmt,
    hireRate: form.hireRate,
    hireAmt: form.hireAmt,
    cveAmt: form.cveAmt,
    ballastBonus: form.ballastBonus,
    lumpsum: form.lumpsum,
    lumpsumQty: form.lumpsumQty,
    marketRate: form.marketRate,
    addCommPercent: form.addCommPercent,
    bFullSpeed: form.bFullSpeed,
    bEcoSpeed1: form.bEcoSpeed1,
    lFullSpeed: form.lFullSpeed,
    lEcoSpeed1: form.lEcoSpeed1,
    bFoFullSpeed: form.bFoFullSpeed,
    lFoFullSpeed: form.lFoFullSpeed,
    bDoFullSpeed: form.bDoFullSpeed,
    lDoFullSpeed: form.lDoFullSpeed,
    pIfoFullSpeed: form.pIfoFullSpeed,
    pWfoFullSpeed: form.pWfoFullSpeed,
    pIdoFullSpeed: form.pIdoFullSpeed,
    pWdoFullSpeed: form.pWdoFullSpeed,
    totalBunkerCost: form.totalBunkerCost,
    totalPortCost: form.totalPortCost,
    revenue: form.revenue,
    voyageEarnings: form.voyageEarnings,
    notes: form.notes,
    ownerId: form.ownerId,
    disponentOwner: form.disponentOwner,
    gasBaltic: form.gasBaltic,
    gasBaseRate: form.gasBaseRate,
    addnlPremium: form.addnlPremium,
    baseRateFloat: form.baseRateFloat,
    baseRateFixed: form.baseRateFixed,
    baseRateAverage: form.baseRateAverage,
    grossFreightFloat: form.grossFreightFloat,
    grossFreightFixed: form.grossFreightFixed,
    grossFreightAverage: form.grossFreightAverage,
    netFreightFloat: form.netFreightFloat,
    netFreightFixed: form.netFreightFixed,
    netFreightAverage: form.netFreightAverage,
    tceFloat: form.tceFloat,
    tceFixed: form.tceFixed,
    tceAverage: form.tceAverage,
    portLegs: (form.portLegs || []).filter((leg) => leg.fromPortId || leg.toPortId),
    cargoRows: filterCargo(form.cargoRows).map((row) => ({ ...row, status: 1 })),
    overageCargoRows: filterCargo(form.overageCargoRows).map((row) => ({ ...row, status: 2 })),
    deadfreightCargoRows: filterCargo(form.deadfreightCargoRows).map((row) => ({ ...row, status: 3 })),
    bunkerRows: (form.bunkerRows || []).filter((row) => row.bunkerGradeId || row.qty),
    orcRows: (form.orcRows || []).filter((row) => row.costId || row.amount),
    otherIncomeRows: (form.otherIncomeRows || []).filter((row) => row.description || row.amount),
    hireRows: (form.hireRows || []).filter((row) => row.hireDays || row.hireRate || row.hireAmt),
    secaBunkerRows: (form.secaBunkerRows || []).filter((row) => row.bunkerGradeId || row.qty),
    consumptionRows: (form.consumptionRows || []).filter(
      (row) => row.bunkerGradeId || row.balSecaFs || row.ladSecaFs,
    ),
    passageLocations: (form.passageLocations || []).filter(
      (row) => row.fromLocation || row.toLocation,
    ),
    freightQtyRows: (form.freightQtyRows || []).filter(
      (row) => row.vendorId || row.quantity || row.agreedGrossFreight,
    ),
    tankerWsRows: (form.tankerWsRows || []).filter(
      (row) => row.freightSpecs || row.minCargoQty || row.totalAmount,
    ),
    offHireRows: (form.offHireRows || [])
      .filter((row) => row.reason || row.days || row.amount)
      .map((row) => ({
        ...row,
        bunkers: (row.bunkers || []).filter((b) => b.bunkerGradeId || b.qty || b.amount),
      })),
    deliveryBunkerRows: (form.deliveryBunkerRows || []).filter(
      (row) => row.bunkerGradeId || row.qty,
    ),
    redeliveryBunkerRows: (form.redeliveryBunkerRows || []).filter(
      (row) => row.bunkerGradeId || row.qty,
    ),
    invoiceRows: (form.invoiceRows || []).filter((row) => row.invoiceId),
    disponentRows: (form.disponentRows || []).filter((row) => row.name),
    voyageEventRows: (form.voyageEventRows || []).filter((row) => row.details || row.eventDate),
  };
}
